### ISSUE TITLE
Bad Request: chat not found

### ISSUE THREAD

**Issue by pavelek** [rossmcdonald/telegram_hook#1]
authorization to boot is ok but following error appear 
Unable to send message, Received error response from Telegram API (error code 400): Bad Request: chat not foundFailed to fire hook: Received error response from Telegram API (error code 400): Bad Request: chat not found

**Comment by olzhas-ilyubayev** [comment]
Use user id instead of username.
You can use [userinfobot](https://telegram.me/userinfobot) to find out your user ID and then use that as the chat ID.
Example:
`tgHook, err := telegram_hook.NewTelegramHook(appName, token, "12345678")`
